services:
  - type: web
    name: windborne-backend
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.11.7
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
